version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 0
      groups:
          nestjs-fastify:
              patterns: ['@nestjs/*', 'fastify', '@fastify/*']
          prisma:
              patterns: ['prisma', '@prisma/*']
          testing:
              patterns: ['vitest', '@vitest/*']
          linting-formatting:
              patterns: ['eslint', '*eslint*', 'prettier', '*prettier*', 'markdownlint*']
          typescript:
              patterns: ['typescript', '@types/*', 'tsconfig-paths']

    - package-ecosystem: 'docker'
      directory: '/.docker'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 0
